config/routes.rb
CaptainMode::Application.routes.draw do
  
  resources :champions, only: [:index, :show]

  resources :lobbies, only: [:create, :show, :index] do
    member do
      post 'register'
      post 'ban'
      post 'pick'
      get  'stream'
    end
  end
  

  

end

app/models/lobby.rb
require 'exceptions'

# TODO: atomic transactions
# TODO: Change picks and bans into relationships with champions

class Lobby < ActiveRecord::Base
  include Wisper::Publisher
  include Tokenable
  
  # Ordered by time of team creation
  # This limit doesn't really prevent anything...
  has_many :teams, -> { order('created_at ASC').limit(2) }, dependent: :destroy

  # Using this to publish the correct event for Redis
  # Should I probably use an observer pattern instead?
  attr_accessor :event_contents

  after_save :publish_event


  state_machine :initial => :team_one_waiting do
    event :register do
      transition :team_one_waiting => :team_two_waiting,
                 :team_two_waiting => :team_one_ban
    end

    event :ban do
      transition :team_one_ban => :team_two_ban,
                 :team_two_ban => :team_one_pick_one
    end

    event :pick do
      transition :team_one_pick_one   => :team_two_pick_one,
                 :team_two_pick_one   => :team_two_pick_two,
                 :team_two_pick_two   => :team_one_pick_two,
                 :team_one_pick_two   => :team_one_pick_three,
                 :team_one_pick_three => :team_two_pick_three,
                 :team_two_pick_three => :team_two_pick_four,
                 :team_two_pick_four  => :team_one_pick_four,
                 :team_one_pick_four  => :team_one_pick_five,
                 :team_one_pick_five  => :team_two_pick_five,
                 :team_two_pick_five  => :done
    end
  end

  # === Utility ===
  # TODO: Rewrite these less crappy...
  def team(team)
    case team
    when :team_one
      return nil if teams.size < 1
      teams[0]
    when :team_two
      return nil if teams.size < 2
      teams[1]
    end
  end

  def bans(team=:both)
    case team
    when :team_one
      return [] if teams.size < 1
      teams[0].bans.map { |b| b.champion }
    when :team_two
      return [] if teams.size < 2
      teams[1].bans.map { |b| b.champion }
    when :both
      [bans(:team_one), bans(:team_two)].flatten
    end
  end

  def picks(team=:both)
    case team
    when :team_one
      return [] if teams.size < 1
      teams[0].picks.map { |p| p.champion }
    when :team_two
      return [] if teams.size < 2
      teams[1].picks.map { |p| p.champion }
    when :both
      [picks(:team_one), picks(:team_two)].flatten
    end
  end

  def captains(team=:both)
    case team
    when :team_one
      return nil if teams.size < 1
      teams[0].captain_id
    when :team_two
      return nil if teams.size < 2
      teams[1].captain_id
    when :both
      return 
      [captains(:team_one), captains(:team_two)]
    end
  end

  def to_param
    self.token
  end
  
  def channel_name
    self.token
  end


  # === Workflow Actions ===

  def register(user)
    unless self.can_register?
      raise Exceptions::InvalidEvent, "Team captains cannot be registered currently"
    end
    
    teams << Team.new(captain_id: user)
    @event_contents = [:register, user]

    super
  end

  def ban(team, name)
    unless self.can_ban?
      raise Exceptions::InvalidEvent, "Teams cannot currently ban"
    end

    champ = Champion.find_by_name!(name)
    team(team).ban(champ)
    
    @event_name = [:ban, name]

    super
  end

  def pick(team, name)
    unless self.can_pick?
      raise Exceptions::InvalidEvent, "Teams cannot currently pick"
    end

    champ = Champion.find_by_name!(name)
    team(team).pick(champ)
    
    @event_name = [:pick, name]
    
    super
  end

  # Returns nil if there's no captain with given id
  def get_team_by_captain(user)
    teams.find { |x| x.team_captain?(user) }
  end
  
  # Returns false if the supplied user is not a registered team captain
  def get_team_symbol(user)
    case teams.find_index { |x| x.team_captain?(user) }
    when 0
      :team_one
    when 1
      :team_two
    else
      false
    end
  end
  
  # Returns :done if there is no longer a team necessary ("done")
  def current_team
    get_team_from_state
  end
  alias_method :current_team?, :current_team

  def current_action
    return self.state_paths.events[0]
  end
  alias_method :current_action?, :current_action

  def remove_listener(listener)
    local_registrations.delete_if { |reg| reg.listener == listener }
  end
  alias_method :unsubscribe, :remove_listener

  private
    
    def build_event_json
      json = {}
      json[:event] = @event_name[0].to_s
      if json[:event] == :pick or json[:event] == :ban
        json[:name] = @event_name[1]
      end
      json[:next] = next_event
    end
    
    def publish_event
      return if @event_name.nil? # Don't publish if it's just a raw save (i.e. creation)
      json = build_event_json
      publish(:update, json)
    end
    
    def next_event
      return :done if self.state == "done"
      
      # First 8 say "team_one" or "team_two" so after that is 'pick' 'ban' or 'register'
      self.state[8..-1]
    end
  
    def get_team_from_state
      return :done if self.state == "done"

      # Return the first 8 characters, will always contain 'team_one' or 'team_two'
      self.state[0,8].to_sym
    end
end

app/controllers/lobbies_controller.rb
require 'exceptions'
require 'sse/writer'

class LobbiesController < ApplicationController
  include ActionController::Live
  
  rescue_from Exceptions::InvalidEvent, :with => :invalid_event
  rescue_from Exceptions::InvalidSession, :with => :invalid_session
  
  def index
    @lobbies = Lobby.all
  end
  
  def create
    @lobby = Lobby.new
    if @lobby.save
      flash[:notice] = 'Lobby successfully created!'
      redirect_to(@lobby)
    else
      flash[:error] = 'Cannot create new lobby. Try again soon.'
      render :index
    end
  end

  # TODO Inform a user if they're a captain (in case of refresh)
  def show
    set_lobby
    @champions = Champion.all
  end
  
  def stream
    set_lobby
    
    response.headers['Content-Type'] = 'text/event-stream'
    LobbyListener.new(@lobby, response.stream).subscribe
  end
  
  def register
    set_lobby
    user = session[:user_id]
    @lobby.register(user)
    render :json => { :message => "Registered as #{team_name(user)}"}, :status => :ok
  end
  
  # TODO Validate champion names
  def ban
    set_lobby
    team = find_team
    name = params[:name]
    @lobby.ban(team, name)
    render :json => { :message => "#{team_name(team)} has banned #{name}"}, :status => :ok
  end
  
  # TODO Validate champion names
  def pick
    set_lobby
    team = find_team
    name = params[:name]
    @lobby.pick(team, name)
    render :json => { :message => "#{team_name(team)} has picked #{name}"}, :status => :ok
  end
  
  private

    def set_lobby
      @lobby = Lobby.find_by_token!(params[:id])
    end
  
    def team_name(team)
      unless team.is_a? Symbol
        team = @lobby.get_team(user)
      end
      team.to_s.titleize
    end
    
    def find_team
      team = @lobby.get_team_by_captain(session[:user_id])
      raise Exceptions::InvalidSession if team.nil?
      team
    end
  
    def invalid_event(error)
      render :json => { :error => error.message }, :status => :unprocessable_entity
    end
    
    def invalid_session(error)
      render :json => { :error => "You are not a team captain" }, :status => :unauthorized
    end
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
end

app/views/lobbies/_champ_info.html.erb
<div class="content champ-info" side="right">
	<% c = @champions.first %>
	<div class="champ-box" type="champ-info">
      <%= champion_portrait_image(c) %>
      <div class="name">
      	<%= c.name %>
      </div>
      <div class="title">
      	<%= c.title %>
      </div>
    </div>
</div>

app/views/lobbies/_team.html.erb
<div class="content team" side="right" id=<%= color %>>
  <h2 class="team-title <%= "#{color}-glow" %>" %><%= color.capitalize %> Team</h2>
  <%= render partial: "team_info", locals: {team: team } %>
  <div class="clear"></div>
</div>

app/views/lobbies/_team_info.html.erb
<div class="bans">
  <h2 class="bans_header">BANS</h2>
  <ul>
    <% team.bans(3).each do |cb| %>
      <li>
      <div class="champ-box" type="bans">
        <%= champion_headshot_image(cb.champion) %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

<div class="picks">
  <ul>
    <% team.picks(5).each do |cp| %>
      <li>
        <div class="champ-box" type="picks">
          <%= champion_portrait_image(cp.champion) %>
        </div
        </div> 
      </li>
    <% end %>
  </ul>
</div>

app/views/lobbies/_timeline.html.erb
<div class="content timeline" side="right">
  Timeline
</div>

app/views/lobbies/create.html.erb
<h1>Lobbies#create</h1>
<p>Find me in app/views/lobbies/create.html.erb</p>

app/views/lobbies/index.html.erb
<h1>Lobbies Index</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
  <% @lobbies.each do |lobby| %>
    <tr>
      <td><%= link_to 'Show', lobby %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create Lobby', lobbies_path, :method => :post %>

app/views/lobbies/show.html.erb
<body>
  <div class="header">
    <h1 class="title">Captain's Mode</h1>
  </div>
  
  <div class="column" type="left">  
    <div class="content champ-select" side="left">
      <ul>
        <% @champions.each do |c| %>
          <li>
            <div class="champ-box" type="champ-select" state=<%= c.name == 'Batman' ? "highlighted" : ""%>>
              <%= champion_headshot_image(c) %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <div class="column">
    <%= render partial: "team", locals: { team: @lobby.team(:team_one), color: "red" } %>

    <div class="vertical_spacer"></div>

    <%= render partial: "timeline" %>

    <div class="vertical_spacer"></div>
  
    <%= render partial: "team", locals: { team: @lobby.team(:team_two), color: "blue" } %>

    <div class="vertical_spacer"></div>
  
    <%= render partial: "champ_info" %>
  </div>

  <div class="clear"></div>
</body>

app/views/lobbies/update.html.erb
<h1>Lobbies#update</h1>
<p>Find me in app/views/lobbies/update.html.erb</p>