config/routes.rb
CaptainMode::Application.routes.draw do
  
  resources :champions, only: [:index, :show]

  resources :lobbies, only: [:create, :show, :index] do
    member do
      post 'register'
      post 'ban'
      post 'pick'
      get  'stream'
    end
  end
  

  

end

app/models/champion.rb
class Champion < ActiveRecord::Base
	has_many :champion_bans, as: :bans
	has_many :champion_picks, as: :picks
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]

  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all

    respond_to do |format|
      # format.json { }
    end
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
    set_champion
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion
      @champion = Champion.find!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_params
      params.require(:champion).permit(:name, :role)
    end
end

app/helpers/champions_helper.rb
module ChampionsHelper

	def champion_headshot_path(c)
		"/images/headshots/#{champion_tag(c)}.jpg"
	end

	def champion_headshot_image(c, options={})
		return "" if c.nil?
		image_tag(champion_headshot_path(c), options)
	end

	def champion_portrait_path(c)
		"/images/portraits/#{champion_tag(c)}.jpg"
	end

	def champion_portrait_image(c, options={})
		return "" if c.nil?
		image_tag(champion_portrait_path(c), options)
	end

	def champion_tag(c)
		c.name.parameterize.underscore
	end
	
end

app/views/champions/_form.html.erb
<%= form_for(@champion) do |f| %>
  <% if @champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% @champion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing champion</h1>

<%= render 'form' %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

app/views/champions/index.html.erb
<h1>Listing champions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= champion.name %></td>
        <td><%= champion.role %></td>
        <td><%= link_to 'Show', champion %></td>
        <td><%= link_to 'Edit', edit_champion_path(champion) %></td>
        <td><%= link_to 'Destroy', champion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion', new_champion_path %>

app/views/champions/new.html.erb
<h1>New champion</h1>

<%= render 'form' %>

<%= link_to 'Back', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @champion.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @champion.role %>
</p>

<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'Back', champions_path %>